### ISSUE TITLE
Incorrect product query results order.

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#685]
**SDK Version**: 3.0

Product search results requested with `.relevance` sort key do not have a deterministic order. Repeated searches with the same query string yield results in a different order every time.

**Comment by dbart01** [comment]
It looks like this is the intended behaviour. That is to say, it's up to ElasticSearch. According to their [documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html), relevance isn't deterministic and the relevance scores of results aren't guaranteed, even for the same the search term. While we can't change this behaviour, I do agree with you that it feels a little unnatural.

**Comment by calebd** [comment]
I don't see anywhere in the ElasticSearch documentation that says relevance results are not deterministic. If the data remains constant, so should the scores for a given query. The data I see coming from the Graph QL API isn't consistent with itself (items vary by up to 10 positions across repeated queries) or with what we see on web search in our shop.

**Comment by dbart01** [comment]
We can definitely look into it but for now, search results using the `.relevance` sort key will remain non-deterministic. I'll keep the issue open to track the investigation.

**Comment by calebd** [comment]
I just realized that I don't have to provide a `sortKey` at all. Now they are deterministic but the results still don't match what we see on the web. Is there any way to get the search API endpoint to return the same data that the `/search` web endpoint uses?

**Comment by dbart01** [comment]
What is the format of your `query` parameter? Can you provide a sample?

**Comment by calebd** [comment]
```
let query = Storefront.buildQuery({
    $0.shop({
        $0.products(first: 100, reverse: true, query: query, {
            $0.productSearchFragment()
        })
    })
})
```

`query` is user provided text taken from a search bar.

If I search for "nomos" on our shop on the web, and do the same in our app against the new SDK, the results are out of order.

Compare the products here https://shop.hodinkee.com/search?q=nomos to these Graph QL results:

```
{
  "data": {
    "shop": {
      "products": {
        "edges": [
          {
            "node": {
              "title": "NOMOS Glashütte Metro Chronometer Limited Edition for HODINKEE"
            }
          },
          {
            "node": {
              "title": "Glossy Dark Brown Alligator Watch Strap"
            }
          },
          {
            "node": {
              "title": "Glossy Navy Blue Alligator Watch Strap"
            }
          },
          {
            "node": {
              "title": "Glossy Chestnut Brown Alligator Watch Strap"
            }
          },
          {
            "node": {
              "title": "Matte Dark Brown Alligator Watch Strap"
            }
          },
          {
            "node": {
              "title": "Matte Light Brown Alligator Watch Strap"
            }
          },
          {
            "node": {
              "title": "Brown Suede Watch Strap"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by dbart01** [comment]
What do you think @mtaher ?

**Comment by mtaher** [comment]
Hi @calebd, thanks for flagging this issue.

Looks like the web and the api have different default sort orders. We're currently investigating the issue.

**Comment by dbart01** [comment]
Fixed.

**Comment by mtaher** [comment]
🎉

**Comment by RishabhTayal** [comment]
@dbart01 I am still getting the right product search results.
