### ISSUE TITLE
Product <null> If he is not in the channel

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#777]
I ran into a problem.
I have a landing page on which I request a list of product ids from my server. But some of these products are not available in the GraphQL Sales Channel
When an array is requested

```graphql
.nodes(ids: itemsArray) { $0
    .onProduct { $0
```

I give full objects by ignoring the SalesChannel

But when I want to get the product by id or handle and it's not in the Sales Channel, I get a null object.

```
<QueryRoot: ["shop": {
     productByHandle = "<null>";
}]>
```

The error is also null.

Is it possible to exclude the products that are not contained in Sales Channel, in general, even when I request an array?

**Comment by dbart01** [comment]
If a product is not in the Mobile App channel, it will be `null`. This is the intended and correct behaviour.

**Comment by aShaforostov** [comment]
Thanks for reply) But why the product object is not null if I request it using an array of nodes?

**Comment by dbart01** [comment]
I apologize, I misunderstood your question. This does seem a little weird, indeed. We'll look into it.

**Comment by dbart01** [comment]
This was an inconsistency in our GraphQL API. The problem has been resolved on our side.

**Comment by pitchourou** [comment]
not fixed yet, still getting Null when using nodes ... on Product ,using 2019-07 api

**Comment by dbart01** [comment]
@pitchourou What's the behaviour you're expecting?
