### ISSUE TITLE
Force unwrap crash

### ISSUE THREAD

**Issue by radyslavkrechet** [Shopify/mobile-buy-sdk-ios#807]
Hi!

There is a crash when we create blog news with name that contains arabic/japan/china special characters. Fix it, please. Below you can see additional information about this crash.

Pod versin: 3.x
File: Article.swift
Line: 305
Code: return URL(string: value)!
Error: force unwrap of nil object
Reason: value is a string of URL address with format like "https://name.myshopify.com/blogs/news/اختبار", strings like this can't be used to create URL class object

Thanks.

**Comment by dbart01** [comment]
Thanks for bringing this up, we're looking into it.

**Comment by dbart01** [comment]
@radyslavkrechet The issue has been fixed on the server. Please verify that it works for your use-case.

**Comment by radyslavkrechet** [comment]
@dbart01 The app still crash if a shop has blog news with next title:

- hindi - एक जल्दी भूरी लोमड़ी
- thai - ทดสอบนะจ๊ะ  
- unicode - Iñtërnâtiônàlizætiøn:snowman::muscle:
- chinese - 北京位於華北平原的西北边缘
- arabic - الظواهر
- cyrillic - Римский император Константин

I think that there is no server side bug because Android SDK doesn't crash in this case. There is a problem with create URL object with String object that contains part that I've listed above.

**Comment by dbart01** [comment]
My apologies, the server changes have gone live _now_. Please verify that it addresses the problem in your application. The issue was related to how unicode characters were encoded, affecting how `Foundation` was parsing URL strings.

**Comment by radyslavkrechet** [comment]
It works fine now, thank you.

**Comment by dbart01** [comment]
Glad to hear 😃
