### ISSUE TITLE
Web Checkout ask Login 

### ISSUE THREAD

**Issue by patelgaurav4u** [Shopify/mobile-buy-sdk-ios#841]
SDK : 3.1.5

i have create checkout and checkoutCustomerAssociate with token.

but still ask login at web checkout.

**Comment by dbart01** [comment]
Providing the customer access token using the `X-Shopify-Customer-Access-Token` header in your request to load the web checkout page should resolve the issue. Please let me know if you run into any problems.

**Comment by ritteraf** [comment]
Dima - I noticed that there is a "customer" value in CheckoutViewModel. Would specifying this during checkout produce the same result?

**Comment by dbart01** [comment]
No, none of the view model classes interact with the API in anyway. They are "view" representations of API models. Setting the header is the only way to "transfer" the logged in state of a customer to the checkout.

**Comment by dbart01** [comment]
You're right. Unfortunately, there's no way to make it work with `SFSafariViewController` as a custom header is required.

**Comment by patelgaurav4u** [comment]
we have pass header but still getting same. webview ask for login

**Comment by ritteraf** [comment]
Hey Dima - I'm loading the checkout URL now in a WKWebView, and it's all working great, but with one problem. Shopify is not detecting the WKWebView as Safari or a mobile browser, and as such, is not presenting the Google Pay or Apple Pay options.

Any idea on how to handle this?

**Comment by patelgaurav4u** [comment]
@ritteraf  can you please share code here?

**Comment by niwinnm** [comment]
This happens when the store has made customer accounts are mandatory during checkout. Basically they have disabled guest checkout option.

Until the ideal solution is available, you guys can ask your clients to enable guest checkout by changing the setting to "Accounts are optional".

**Comment by niwinnm** [comment]
This happens when the store has made it mandatory, for the customers, to have an account for completing a checkout. In simple terms, they have don't have Guest checkout.

Until the ideal solution is available, you can ask your clients to enable guest checkout by changing the setting to "Accounts are optional".

**Comment by ritteraf** [comment]
I think I understand what @patelgaurav4u is speaking of. I tried passing the authorization header in my URLRequest that loads in a WKWebView with the following code:
```
urlRequest.setValue(activeCustomerAccessToken, forHTTPHeaderField: "X-Shopify-Customer-Access-Token")
webKitView.load(urlRequest)
```

I double and triple checked to make sure the customer token being passed was correct. The resulting loaded page still asks for a login. @dbart01 you mentioned to let you know if this approach was not working, and it appears it is not.

**Comment by dbart01** [comment]
This is something we're looking into. I'll share more details as they come in.

**Comment by davidcorbin** [comment]
Having the same issue as @ritteraf above. The checkout page still shows the "Log In" button rather than the customer's account even when the `X-Shopify-Customer-Access-Token` header and corresponding token is sent.

**Comment by markj** [comment]
I have the same issue. I've tried passing the token in for the first page load of the web checkout URL without success. I've also forced that token to be passed to all subsequent requests to shopify but that doesn't work either...

**Comment by ritteraf** [comment]
For anyone who's interested, it seems that this issue has been addressed with the latest release. Yay!

**Comment by dbart01** [comment]
@ritteraf is correct, the issue has been addressed on our backend. Please note that this is not related to any version of the SDK. It was an issue in web checkout that has now been fixed.

**Comment by venkataseshaiahudatha** [comment]
> Providing the customer access token using the `X-Shopify-Customer-Access-Token` header in your request to load the web checkout page should resolve the issue. Please let me know if you run into any problems with this approach.

can you please help me to do the same in Android

**Comment by caisd1998** [comment]
> @ritteraf is correct, the issue has been addressed on our backend. Please note that this is not related to any version of the SDK. It was an issue in web checkout that has now been fixed.

@dbart01 I'm still seeing this issue, so I have to use WKWebview or UIWebview and add "X-Shopify-Customer-Access-Token". But this solution has an issue compared to using SFSafariViewController, it doesn't support Apple Pay.

**Comment by dbart01** [comment]
@caisd1998 Are you seeing the customer login issue in `WKWebView` or is your concern only surrounding Apple Pay?

**Comment by caisd1998** [comment]
@dbart01 My main concern is that I can't get both working at the same time.
If I use the recommend SFSafariViewController, Apple Pay is showing up in Express checkout, but customer login has issue.
If I use WKWebview with http header "X-Shopify-Customer-Access-Token", customer login has no issue, but Apple Pay is not showing up. 
Both are good for customer, it's hard for us to just have either one. According to Apple's [Apple Pay on the Web](https://developer.apple.com/documentation/apple_pay_on_the_web) document, SFSafariViewController is the only way for Apple Pay on the Web, so I hope you or your team can find a way to let us use SFSafariViewController without customer login issue. Thanks.

> In iOS, Apple Pay is supported in Safari and in SFSafariViewController objects.

**Comment by dbart01** [comment]
We're aware that Apple Pay and customer access token can't be combined with the currently implementation. Unfortunately, I can't offer a resolution at this time but we will take this into consideration in the future.

**Comment by Kieran-madefresh** [comment]
Hi @dbart01, just wondering if there are any updates on this? 

I also want to be able to pass in `X-Shopify-Customer-Access-Token` to check out a logged in user, and **also** support Apple Pay during checkout.

If we choose Apple Pay over passing in the access token to log the user in, and if "Accounts are required" is turned on for the store, it becomes an even more confusing user experience, because we ask the user to log in natively within the app, then when presented with the checkout, the user is presented with a username & password field for the website to log in with no mention of the checkout at all.

Is there any way we could pass the users `X-Shopify-Customer-Access-Token` in the checkout mutation that returns the `webURL`?

**Comment by Kieran-madefresh** [comment]
Nevermind as of [Safari 13](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes), Apple Pay is now supported in WKWebView, just implemented it and it works.

**Comment by ksmks0921** [comment]
I have tried to use WKWebView for webcheckout. But I can not see Apple pay button

**Comment by ksmks0921** [comment]
I have tried to use SFSafariViewController for web checkout. 
But I can not add X-Shopify-Customer-Access-Token.
Please help me with this issue.

**Comment by RoyalAdvisor** [comment]
> Providing the customer access token using the `X-Shopify-Customer-Access-Token` header in your request to load the web checkout page should resolve the issue. Please let me know if you run into any problems with this approach.

Working on a react native app consuming the storefront API and man this is the solution I was looking for. Been struggling for months to authenticate a user's checkout. Big thanks bro.

**Comment by patelgaurav4u** [comment]
https://github.com/react-native-webview/react-native-webview/blob/4197bb42ce79406ff20c7e5637f78e44ca45474c/docs/Reference.md#source
